In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/train_timeseries.csv')

In [ ]:
test_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/test_timeseries.csv')

In [ ]:
validation_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/validation_timeseries.csv')

In [ ]:
x_train = pd.read_csv('/content/drive/Shareddrives/1:1 Srikar Eranky/x_train.csv')

In [ ]:
x_train_sample = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/x_train_two.csv')

In [ ]:
train_data_categorical = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/x_train_categorical.csv')

In [ ]:
train_df_bands = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/x_train_bands.csv')

In [ ]:
balanced_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/balanced_data (4).csv')

In [ ]:
balanced_bands_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/balanced_bands_data.csv')

In [ ]:
balanced_bands_label_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/balanced_bands_label.csv')

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19300680 entries, 0 to 19300679
Data columns (total 21 columns):
 #   Column       Dtype  
---  ------       -----  
 0   fips         int64  
 1   date         object 
 2   PRECTOT      float64
 3   PS           float64
 4   QV2M         float64
 5   T2M          float64
 6   T2MDEW       float64
 7   T2MWET       float64
 8   T2M_MAX      float64
 9   T2M_MIN      float64
 10  T2M_RANGE    float64
 11  TS           float64
 12  WS10M        float64
 13  WS10M_MAX    float64
 14  WS10M_MIN    float64
 15  WS10M_RANGE  float64
 16  WS50M        float64
 17  WS50M_MAX    float64
 18  WS50M_MIN    float64
 19  WS50M_RANGE  float64
 20  score        float64
dtypes: float64(19), int64(1), object(1)
memory usage: 3.0+ GB


In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2271948 entries, 0 to 2271947
Data columns (total 21 columns):
 #   Column       Dtype  
---  ------       -----  
 0   fips         int64  
 1   date         object 
 2   PRECTOT      float64
 3   PS           float64
 4   QV2M         float64
 5   T2M          float64
 6   T2MDEW       float64
 7   T2MWET       float64
 8   T2M_MAX      float64
 9   T2M_MIN      float64
 10  T2M_RANGE    float64
 11  TS           float64
 12  WS10M        float64
 13  WS10M_MAX    float64
 14  WS10M_MIN    float64
 15  WS10M_RANGE  float64
 16  WS50M        float64
 17  WS50M_MAX    float64
 18  WS50M_MIN    float64
 19  WS50M_RANGE  float64
 20  score        float64
dtypes: float64(19), int64(1), object(1)
memory usage: 364.0+ MB


In [ ]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275680 entries, 0 to 275679
Data columns (total 21 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   fips         275680 non-null  int64  
 1   date         275680 non-null  object 
 2   PRECTOT      275680 non-null  float64
 3   PS           275680 non-null  float64
 4   QV2M         275680 non-null  float64
 5   T2M          275680 non-null  float64
 6   T2MDEW       275680 non-null  float64
 7   T2MWET       275680 non-null  float64
 8   T2M_MAX      275680 non-null  float64
 9   T2M_MIN      275680 non-null  float64
 10  T2M_RANGE    275680 non-null  float64
 11  TS           275680 non-null  float64
 12  WS10M        275680 non-null  float64
 13  WS10M_MAX    275680 non-null  float64
 14  WS10M_MIN    275680 non-null  float64
 15  WS10M_RANGE  275680 non-null  float64
 16  WS50M        275680 non-null  float64
 17  WS50M_MAX    275680 non-null  float64
 18  WS50M_MIN    275680 non-

In [ ]:
x_train_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55136 entries, 0 to 55135
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   fips         55136 non-null  int64  
 1   date         55136 non-null  object 
 2   PRECTOT      55136 non-null  float64
 3   PS           55136 non-null  float64
 4   QV2M         55136 non-null  float64
 5   T2M          55136 non-null  float64
 6   T2MDEW       55136 non-null  float64
 7   T2MWET       55136 non-null  float64
 8   T2M_MAX      55136 non-null  float64
 9   T2M_MIN      55136 non-null  float64
 10  T2M_RANGE    55136 non-null  float64
 11  TS           55136 non-null  float64
 12  WS10M        55136 non-null  float64
 13  WS10M_MAX    55136 non-null  float64
 14  WS10M_MIN    55136 non-null  float64
 15  WS10M_RANGE  55136 non-null  float64
 16  WS50M        55136 non-null  float64
 17  WS50M_MAX    55136 non-null  float64
 18  WS50M_MIN    55136 non-null  float64
 19  WS50

In [ ]:
train_data_categorical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55136 entries, 0 to 55135
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   fips         55136 non-null  int64  
 1   date         55136 non-null  object 
 2   PRECTOT      55136 non-null  float64
 3   PS           55136 non-null  float64
 4   QV2M         55136 non-null  float64
 5   T2M          55136 non-null  float64
 6   T2MDEW       55136 non-null  float64
 7   T2MWET       55136 non-null  float64
 8   T2M_MAX      55136 non-null  float64
 9   T2M_MIN      55136 non-null  float64
 10  T2M_RANGE    55136 non-null  float64
 11  TS           55136 non-null  float64
 12  WS10M        55136 non-null  float64
 13  WS10M_MAX    55136 non-null  float64
 14  WS10M_MIN    55136 non-null  float64
 15  WS10M_RANGE  55136 non-null  float64
 16  WS50M        55136 non-null  float64
 17  WS50M_MAX    55136 non-null  float64
 18  WS50M_MIN    55136 non-null  float64
 19  WS50

In [ ]:
train_df_bands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275680 entries, 0 to 275679
Data columns (total 22 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   fips         275680 non-null  int64  
 1   date         275680 non-null  object 
 2   PRECTOT      275680 non-null  float64
 3   PS           275680 non-null  float64
 4   QV2M         275680 non-null  float64
 5   T2M          275680 non-null  float64
 6   T2MDEW       275680 non-null  float64
 7   T2MWET       275680 non-null  float64
 8   T2M_MAX      275680 non-null  float64
 9   T2M_MIN      275680 non-null  float64
 10  T2M_RANGE    275680 non-null  float64
 11  TS           275680 non-null  float64
 12  WS10M        275680 non-null  float64
 13  WS10M_MAX    275680 non-null  float64
 14  WS10M_MIN    275680 non-null  float64
 15  WS10M_RANGE  275680 non-null  float64
 16  WS50M        275680 non-null  float64
 17  WS50M_MAX    275680 non-null  float64
 18  WS50M_MIN    275680 non-

In [ ]:
balanced_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18553 entries, 0 to 18552
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   fips         18553 non-null  int64  
 1   date         18553 non-null  object 
 2   PRECTOT      18553 non-null  float64
 3   PS           18553 non-null  float64
 4   QV2M         18553 non-null  float64
 5   T2M          18553 non-null  float64
 6   T2MDEW       18553 non-null  float64
 7   T2MWET       18553 non-null  float64
 8   T2M_MAX      18553 non-null  float64
 9   T2M_MIN      18553 non-null  float64
 10  T2M_RANGE    18553 non-null  float64
 11  TS           18553 non-null  float64
 12  WS10M        18553 non-null  float64
 13  WS10M_MAX    18553 non-null  float64
 14  WS10M_MIN    18553 non-null  float64
 15  WS10M_RANGE  18553 non-null  float64
 16  WS50M        18553 non-null  float64
 17  WS50M_MAX    18553 non-null  float64
 18  WS50M_MIN    18553 non-null  float64
 19  WS50

# Miscellaneous Data Analysis - Disregard

In [ ]:
balanced_df['label'] = bands
balanced_df

fips        date  PRECTOT      PS  ...  WS50M_MIN  WS50M_RANGE  score  label
0      40049  2007-02-13     4.33   98.02  ...       8.63         7.81      0      A
1      30067  2011-06-14     2.47   78.25  ...       2.18         6.09      0      A
2      53041  2007-03-27     5.21   94.43  ...       2.13         3.04      0      A
3      51015  2000-10-24     0.40   95.61  ...       0.97         2.00      0      A
4      29510  2014-09-16     0.04  100.09  ...       1.21         4.43      0      A
...      ...         ...      ...     ...  ...        ...          ...    ...    ...
18548  31013  2013-01-01     0.06   87.37  ...       5.11         4.40      5      C
18549  47153  2007-08-14     0.00   97.37  ...       1.36         3.16      5      C
18550  51141  2002-09-24     0.07   96.77  ...       1.13         2.99      5      C
18551  13137  2007-11-20     0.00   95.45  ...       2.10         1.82      5      C
18552  48179  2011-09-20     0.03   91.91  ...       3.44         7.14      5      C

[18553 rows x 22 columns]

In [ ]:
balanced_df.to_csv('balanced_bands_data.csv',index=False)

In [ ]:
balanced_df[balanced_df['score']==4]

fips        date  PRECTOT      PS  ...  WS50M_MIN  WS50M_RANGE  score  label
16453   1045  2012-05-29     0.66  100.01  ...       3.72         3.06      4      C
16454  13261  2011-12-06     1.46  100.03  ...       4.52         2.44      4      C
16455  48149  2009-04-07     0.00  101.38  ...       2.19         7.68      4      C
16456  49037  2003-01-07     0.00   82.90  ...       2.16         3.49      4      C
16457  51067  2002-07-09     2.73   98.09  ...       3.18         2.58      4      C
...      ...         ...      ...     ...  ...        ...          ...    ...    ...
18070  35053  2003-12-30     0.08   83.76  ...       1.29         2.61      4      C
18071  13245  2011-10-04     0.01  100.89  ...       2.42         3.29      4      C
18072  19149  2013-02-19     0.00   97.73  ...       5.27         9.23      4      C
18073  29047  2012-07-24     0.00   98.08  ...       5.23         3.47      4      C
18074  30111  2003-10-28     9.78   87.46  ...       2.68        12.19      4      C

[1622 rows x 22 columns]

In [ ]:
train_df_bands

fips        date  PRECTOT      PS  ...  WS50M_MIN  WS50M_RANGE  score  label
0       48115  2012-07-24     0.19   91.73  ...       6.24         3.61      3      B
1       48185  2010-02-09     0.13  101.30  ...       4.69         5.08      0      A
2        1009  2004-02-17     0.02  100.54  ...       0.58         4.79      0      A
3       21049  2015-10-06     0.01   98.19  ...       1.33         4.21      0      A
4       27073  2005-04-19     2.31   96.00  ...       2.47         6.84      0      A
...       ...         ...      ...     ...  ...        ...          ...    ...    ...
275675  20051  2011-12-13     3.41   94.49  ...       4.41         3.88      1      A
275676  48247  2001-04-24     1.54  100.26  ...       6.14         7.27      1      A
275677  19101  2000-01-25     0.05   99.60  ...       6.55         4.45      2      B
275678  23029  2010-10-12     0.00  100.28  ...       0.61         5.09      0      A
275679  48361  2003-07-15     5.15  101.31  ...       5.11         3.84      0      A

[275680 rows x 22 columns]

In [ ]:
#balanced dataset with only label column
balanced_bands_label_df

fips        date  PRECTOT  ...  WS50M_MIN  WS50M_RANGE  label
0      40049  2007-02-13     4.33  ...       8.63         7.81      A
1      30067  2011-06-14     2.47  ...       2.18         6.09      A
2      53041  2007-03-27     5.21  ...       2.13         3.04      A
3      51015  2000-10-24     0.40  ...       0.97         2.00      A
4      29510  2014-09-16     0.04  ...       1.21         4.43      A
...      ...         ...      ...  ...        ...          ...    ...
18548  31013  2013-01-01     0.06  ...       5.11         4.40      C
18549  47153  2007-08-14     0.00  ...       1.36         3.16      C
18550  51141  2002-09-24     0.07  ...       1.13         2.99      C
18551  13137  2007-11-20     0.00  ...       2.10         1.82      C
18552  48179  2011-09-20     0.03  ...       3.44         7.14      C

[18553 rows x 21 columns]

In [ ]:
#original balanced dataset
balanced_bands_df

fips        date  PRECTOT      PS  ...  WS50M_MIN  WS50M_RANGE  score  label
0      40049  2007-02-13     4.33   98.02  ...       8.63         7.81      0      A
1      30067  2011-06-14     2.47   78.25  ...       2.18         6.09      0      A
2      53041  2007-03-27     5.21   94.43  ...       2.13         3.04      0      A
3      51015  2000-10-24     0.40   95.61  ...       0.97         2.00      0      A
4      29510  2014-09-16     0.04  100.09  ...       1.21         4.43      0      A
...      ...         ...      ...     ...  ...        ...          ...    ...    ...
18548  31013  2013-01-01     0.06   87.37  ...       5.11         4.40      5      C
18549  47153  2007-08-14     0.00   97.37  ...       1.36         3.16      5      C
18550  51141  2002-09-24     0.07   96.77  ...       1.13         2.99      5      C
18551  13137  2007-11-20     0.00   95.45  ...       2.10         1.82      5      C
18552  48179  2011-09-20     0.03   91.91  ...       3.44         7.14      5      C

[18553 rows x 22 columns]

In [ ]:
balanced_bands_label_df.to_csv('balanced_bands_label.csv',index=False)

In [ ]:
category_a_df = balanced_bands_df[balanced_bands_df['label']=='A']#label A taken from original balanced dataset
category_a_df.to_csv('category_a_data.csv',index=False)

In [ ]:
category_b_df = balanced_bands_df[balanced_bands_df['label']=='B']#label B taken from original balanced dataset
category_b_df.to_csv('category_b_data.csv',index=False)

In [ ]:
category_c_df = balanced_bands_df[balanced_bands_df['label']=='C']#label C taken from original balanced dataset
category_c_df.to_csv('category_c_data.csv',index=False)

In [ ]:
category_a_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/category_a_data.csv')
category_b_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/category_b_data.csv')
category_c_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/category_c_data.csv')

In [ ]:
len(category_a_df)

7853

In [ ]:
len(category_b_df)

8600

In [ ]:
len(category_c_df)

2100

# Formatting, Balancing Test Data

In [ ]:
test_df = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/test_timeseries.csv')

In [ ]:
test_df = test_df.dropna()

In [ ]:
test_df['score'] = test_df['score'].astype(int)
test_df

fips        date  PRECTOT  ...  WS50M_MIN  WS50M_RANGE  score
0         1001  2019-01-01     2.25  ...       1.23         2.78      0
7         1001  2019-01-08     0.05  ...       3.67         2.85      0
14        1001  2019-01-15     0.00  ...       2.39         1.75      0
21        1001  2019-01-22     0.03  ...       5.01         3.55      0
28        1001  2019-01-29     5.79  ...       3.60         3.35      0
...        ...         ...      ...  ...        ...          ...    ...
2271917  56043  2020-12-01     1.24  ...       5.13         5.21      3
2271924  56043  2020-12-08     0.00  ...       3.85         2.45      3
2271931  56043  2020-12-15     0.14  ...       2.83         3.66      3
2271938  56043  2020-12-22     1.64  ...       9.05         8.25      3
2271945  56043  2020-12-29     0.00  ...       0.29         7.37      3

[326340 rows x 21 columns]

In [ ]:
bands = []
for category in test_df['score']:
  if category == 0 or category == 1:
    bands.append('A')
  elif category == 2 or category == 3:
    bands.append('B')
  else:
    bands.append('C')
print(bands)

['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',

In [ ]:
test_df['label'] = bands
test_df

fips        date  PRECTOT  ...  WS50M_RANGE  score  label
0         1001  2019-01-01     2.25  ...         2.78      0      A
7         1001  2019-01-08     0.05  ...         2.85      0      A
14        1001  2019-01-15     0.00  ...         1.75      0      A
21        1001  2019-01-22     0.03  ...         3.55      0      A
28        1001  2019-01-29     5.79  ...         3.35      0      A
...        ...         ...      ...  ...          ...    ...    ...
2271917  56043  2020-12-01     1.24  ...         5.21      3      B
2271924  56043  2020-12-08     0.00  ...         2.45      3      B
2271931  56043  2020-12-15     0.14  ...         3.66      3      B
2271938  56043  2020-12-22     1.64  ...         8.25      3      B
2271945  56043  2020-12-29     0.00  ...         7.37      3      B

[326340 rows x 22 columns]

In [ ]:
category_a_test = test_df[test_df['label']=='A']
category_a_test

fips        date  PRECTOT  ...  WS50M_RANGE  score  label
0         1001  2019-01-01     2.25  ...         2.78      0      A
7         1001  2019-01-08     0.05  ...         2.85      0      A
14        1001  2019-01-15     0.00  ...         1.75      0      A
21        1001  2019-01-22     0.03  ...         3.55      0      A
28        1001  2019-01-29     5.79  ...         3.35      0      A
...        ...         ...      ...  ...          ...    ...    ...
2271728  56043  2020-05-26     0.05  ...         5.21      0      A
2271735  56043  2020-06-02     0.33  ...         5.71      1      A
2271742  56043  2020-06-09     0.34  ...         6.76      1      A
2271770  56043  2020-07-07     0.02  ...         8.46      1      A
2271777  56043  2020-07-14     0.19  ...         6.73      1      A

[300769 rows x 22 columns]

In [ ]:
category_b_test = test_df[test_df['label']=='B']
category_b_test

fips        date  PRECTOT  ...  WS50M_RANGE  score  label
280       1001  2019-10-08     0.04  ...         4.29      2      B
287       1001  2019-10-15    23.78  ...         3.78      2      B
294       1001  2019-10-22     2.62  ...         4.09      2      B
301       1001  2019-10-29     1.50  ...         4.27      2      B
308       1001  2019-11-05     0.00  ...         5.41      2      B
...        ...         ...      ...  ...          ...    ...    ...
2271917  56043  2020-12-01     1.24  ...         5.21      3      B
2271924  56043  2020-12-08     0.00  ...         2.45      3      B
2271931  56043  2020-12-15     0.14  ...         3.66      3      B
2271938  56043  2020-12-22     1.64  ...         8.25      3      B
2271945  56043  2020-12-29     0.00  ...         7.37      3      B

[23389 rows x 22 columns]

In [ ]:
category_c_test = test_df[test_df['label']=='C']
category_c_test

fips        date  PRECTOT     PS  ...  WS50M_MIN  WS50M_RANGE  score  label
49635     4001  2020-10-20     0.00  80.33  ...       0.36         3.42      4      C
49642     4001  2020-10-27     1.64  80.04  ...       0.31         7.50      4      C
49649     4001  2020-11-03     0.00  80.80  ...       1.16         5.59      4      C
49656     4001  2020-11-10     0.00  80.19  ...       0.44         5.21      4      C
49663     4001  2020-11-17     0.00  80.91  ...       5.77         4.39      4      C
...        ...         ...      ...    ...  ...        ...          ...    ...    ...
2025570  49055  2020-12-01     0.00  83.03  ...       4.59         5.59      4      C
2025577  49055  2020-12-08     0.00  83.63  ...       0.43         3.31      4      C
2025584  49055  2020-12-15     0.00  82.87  ...       1.39         6.88      4      C
2025591  49055  2020-12-22     0.00  82.37  ...       4.79         8.61      4      C
2025598  49055  2020-12-29     1.04  82.41  ...       2.59         5.16      4      C

[2182 rows x 22 columns]

In [ ]:
category_c_test[category_c_test['score']==5]

fips        date  PRECTOT     PS  ...  WS50M_MIN  WS50M_RANGE  score  label
49677     4001  2020-12-01     0.00  80.39  ...       2.84         8.72      5      C
49684     4001  2020-12-08     0.00  81.04  ...       2.57         4.89      5      C
51132     4005  2020-11-24     0.00  80.97  ...       2.41         3.55      5      C
51139     4005  2020-12-01     0.00  81.48  ...       3.82         4.69      5      C
51146     4005  2020-12-08     0.00  81.97  ...       3.34         1.85      5      C
...        ...         ...      ...    ...  ...        ...          ...    ...    ...
2024839  49053  2020-12-01     0.00  83.08  ...       3.10         6.27      5      C
2024846  49053  2020-12-08     0.00  83.49  ...       2.81         6.52      5      C
2024853  49053  2020-12-15     0.03  82.99  ...       3.03         3.87      5      C
2024860  49053  2020-12-22     0.00  82.59  ...       4.56         5.00      5      C
2024867  49053  2020-12-29     1.77  82.57  ...       2.14         6.34      5      C

[225 rows x 22 columns]

In [ ]:
balanced_test_df = pd.DataFrame()
for category in np.unique(test_df['label']):
  if category == 'A':
    sample_per_category = 2182
  elif category == 'B':
    sample_per_category = 2182
  else:
    sample_per_category = 2182
  x_test_subset = test_df[test_df['label'] == category]
  x_test_subset = x_test_subset.sample(n=sample_per_category,replace=False)
  balanced_test_df = pd.concat([balanced_test_df,x_test_subset],ignore_index=True)#This is the test dataset that I used

In [ ]:
balanced_test_df.to_csv('balanced_test_data.csv',index=False)

In [ ]:
#attempting to balanced the test data for category A
balanced_test_df_a = pd.DataFrame()
for category in np.unique(category_a_test['score']):
  if category == 0:
    sample_per_category = 1000
  else:
    sample_per_category = 1000
  x_test_a_subset = category_a_test[category_a_test['score'] == category]
  x_test_a_subset = x_test_a_subset.sample(n=sample_per_category,replace=False)
  balanced_test_df_a = pd.concat([balanced_test_df_a,x_test_a_subset],ignore_index=True)

In [ ]:
balanced_test_df_a.to_csv('balanced_test_data_a.csv',index=False)

In [ ]:
balanced_test_df_b = pd.DataFrame()
for category in np.unique(category_b_test['score']):
  if category == 2:
    sample_per_category = 1300
  else:
    sample_per_category = 1300
  x_test_b_subset = category_b_test[category_b_test['score'] == category]
  x_test_b_subset = x_test_b_subset.sample(n=sample_per_category,replace=False)
  balanced_test_df_b = pd.concat([balanced_test_df_b,x_test_b_subset],ignore_index=True)

In [ ]:
balanced_test_df_b.to_csv('balanced_test_data_b.csv',index=False)

In [ ]:
balanced_test_df_c = pd.DataFrame()
for category in np.unique(category_c_test['score']):
  if category == 4:
    sample_per_category = 225
  else:
    sample_per_category = 225
  x_test_c_subset = category_c_test[category_c_test['score'] == category]
  x_test_c_subset = x_test_c_subset.sample(n=sample_per_category,replace=False)
  balanced_test_df_c = pd.concat([balanced_test_df_c,x_test_c_subset],ignore_index=True)

In [ ]:
balanced_test_df_c.to_csv('balanced_test_data_c.csv',index=False)


# Failed first attempt for all 4 AI's - Disregard This


In [ ]:
#Top level AI
from sklearn.ensemble import RandomForestClassifier
x_train = balanced_bands_label_df.drop(['label','date'],axis=1)
y_train = balanced_bands_label_df['label']

In [ ]:
rfc = RandomForestClassifier(n_estimators=1000,max_depth=100)

In [ ]:
rfc.fit(x_train,y_train)

RandomForestClassifier(max_depth=100, n_estimators=1000)

In [ ]:
x_test = top_level_sample.drop(['label','date','score'],axis=1)
y_test = top_level_sample['label']

In [ ]:
preds = rfc.predict(x_test)

In [ ]:
#sample test data for only top level AI, then use the rest of the test data for the specific category predictions
#Category AIs
x_train_A = category_a_df.drop(['date','label','score'],axis=1)
y_train_A = category_a_df['score']
x_train_B = category_b_df.drop(['date','label','score'],axis=1)
y_train_B = category_b_df['score']
x_train_C = category_c_df.drop(['date','label','score'],axis=1)
y_train_C = category_c_df['score']

In [ ]:
#Category A AI
rfc_A = RandomForestClassifier(n_estimators=1000,max_depth=100)
rfc_A.fit(x_train_A,y_train_A)

RandomForestClassifier(max_depth=100, n_estimators=1000)

In [ ]:
x_test_A = categorical_a_test.drop(['date','label','score'],axis=1)
y_test_A = categorical_a_test['score']
preds_A = rfc_A.predict(x_test_A)

In [ ]:
print(confusion_matrix(y_test_A,preds_A))
print(classification_report(y_test_A,preds_A))

[[3359 2349]
 [ 290  502]]
              precision    recall  f1-score   support

           0       0.92      0.59      0.72      5708
           1       0.18      0.63      0.28       792

    accuracy                           0.59      6500
   macro avg       0.55      0.61      0.50      6500
weighted avg       0.83      0.59      0.66      6500



In [ ]:
#Category B AI
rfc_B = RandomForestClassifier(n_estimators=1000,max_depth=100)
rfc_B.fit(x_train_B,y_train_B)

RandomForestClassifier(max_depth=100, n_estimators=1000)

In [ ]:
x_test_B = categorical_b_test.drop(['date','label','score'],axis=1)
y_test_B = categorical_b_test['score']
preds_B = rfc_B.predict(x_test_B)

In [ ]:
print(confusion_matrix(y_test_B,preds_B))
print(classification_report(y_test_B,preds_B))

[[4240 1239]
 [1480  541]]
              precision    recall  f1-score   support

           2       0.74      0.77      0.76      5479
           3       0.30      0.27      0.28      2021

    accuracy                           0.64      7500
   macro avg       0.52      0.52      0.52      7500
weighted avg       0.62      0.64      0.63      7500



In [ ]:
#Category C AI
rfc_C = RandomForestClassifier(n_estimators=1000,max_depth=100)
rfc_C.fit(x_train_C,y_train_C)

RandomForestClassifier(max_depth=100, n_estimators=1000)

In [ ]:
x_test_C = categorical_c_test.drop(['date','label','score'],axis=1)
y_test_C = categorical_c_test['score']
preds_C = rfc_C.predict(x_test_C)

In [ ]:
print(confusion_matrix(y_test_C,preds_C))
print(classification_report(y_test_C,preds_C))

[[1009    4]
 [ 139    1]]
              precision    recall  f1-score   support

           4       0.88      1.00      0.93      1013
           5       0.20      0.01      0.01       140

    accuracy                           0.88      1153
   macro avg       0.54      0.50      0.47      1153
weighted avg       0.80      0.88      0.82      1153



In [ ]:
#sample data invidually for each category and tune for accuracy

# Formatting, Balancing Train Data

In [ ]:
#Create labels for each column - A, B, C
x_train = pd.read_csv('/content/drive/Shareddrives/1:1 Srikar Eranky/x_train.csv')
x_train['score'] = x_train['score'].astype(int)

bands = []
for category in x_train['score']:
  if category == 0 or category == 1:
    bands.append('A')
  elif category == 2 or category == 3:
    bands.append('B')
  else:
    bands.append('C')

x_train['label'] = bands
x_train

fips        date  PRECTOT      PS   QV2M    T2M  T2MDEW  T2MWET  \
0       48115  2012-07-24     0.19   91.73  11.61  29.62   14.89   14.89   
1       48185  2010-02-09     0.13  101.30   3.17   2.71   -2.53   -2.46   
2        1009  2004-02-17     0.02  100.54   4.51   5.35    2.38    2.39   
3       21049  2015-10-06     0.01   98.19   9.04  18.85   12.16   12.16   
4       27073  2005-04-19     2.31   96.00  10.55  17.13   14.18   14.19   
...       ...         ...      ...     ...    ...    ...     ...     ...   
275675  20051  2011-12-13     3.41   94.49   5.23   3.70    3.53    3.53   
275676  48247  2001-04-24     1.54  100.26   9.68  19.95   13.31   13.31   
275677  19101  2000-01-25     0.05   99.60   1.30  -9.49  -13.05  -12.83   
275678  23029  2010-10-12     0.00  100.28   5.53   9.16    5.20    5.20   
275679  48361  2003-07-15     5.15  101.31  18.54  26.89   24.01   24.01   

        T2M_MAX  T2M_MIN  ...  WS10M  WS10M_MAX  WS10M_MIN  WS10M_RANGE  \
0         36.43    22.78  ...   5.85       7.48       4.13         3.35   
1          6.82    -0.42  ...   5.04       6.71       2.08         4.62   
2         10.97     0.24  ...   1.25       1.83       0.39         1.44   
3         26.64    13.14  ...   2.14       2.62       1.01         1.61   
4         21.57    13.44  ...   4.79       6.88       1.46         5.42   
...         ...      ...  ...    ...        ...        ...          ...   
275675     6.55     1.13  ...   4.01       5.76       2.38         3.38   
275676    26.30    15.71  ...   6.12      10.40       3.07         7.32   
275677    -3.92   -14.88  ...   6.90       9.03       4.90         4.12   
275678    13.66     5.37  ...   1.48       3.46       0.56         2.90   
275679    29.44    25.04  ...   4.86       6.07       2.72         3.35   

        WS50M  WS50M_MAX  WS50M_MIN  WS50M_RANGE  score  label  
0        7.83       9.85       6.24         3.61      3      B  
1        7.67       9.77       4.69         5.08      0      A  
2        2.90       5.37       0.58         4.79      0      A  
3        3.97       5.54       1.33         4.21      0      A  
4        6.73       9.32       2.47         6.84      0      A  
...       ...        ...        ...          ...    ...    ...  
275675   6.14       8.29       4.41         3.88      1      A  
275676   8.41      13.41       6.14         7.27      1      A  
275677   9.12      10.99       6.55         4.45      2      B  
275678   2.22       5.71       0.61         5.09      0      A  
275679   7.59       8.95       5.11         3.84      0      A  

[275680 rows x 22 columns]

In [ ]:
len(x_train[x_train['score']==5])

2111

In [ ]:

balanced_df = pd.DataFrame()
for category in np.unique(x_train['label']):
  if category == 'A':
    sample_per_category = 10099
  elif category == 'B':
    sample_per_category = 10099
  else:
    sample_per_category = 10099
  x_train_subset = x_train[x_train['label'] == category]
  x_train_subset = x_train_subset.sample(n=sample_per_category,replace=False,random_state=24)
  balanced_df = pd.concat([balanced_df,x_train_subset],ignore_index=True)
"""
balanced_df = pd.DataFrame()
for category in np.unique(x_train['score']):
  if category == 0:
    sample_per_category = 2111
  elif category == 1:
    sample_per_category = 2111
  elif category == 2:
    sample_per_category = 2111
  elif category == 3:
    sample_per_category = 2111
  elif category == 4:
    sample_per_category = 2111
  else:
    sample_per_category = 2111
  x_train_subset = x_train[x_train['score'] == category]
  x_train_subset = x_train_subset.sample(n=sample_per_category,replace=False)
  balanced_df = pd.concat([balanced_df,x_train_subset],ignore_index=True)
  """

"\nbalanced_df = pd.DataFrame()\nfor category in np.unique(x_train['score']):\n  if category == 0:\n    sample_per_category = 2111\n  elif category == 1:\n    sample_per_category = 2111\n  elif category == 2:\n    sample_per_category = 2111\n  elif category == 3:\n    sample_per_category = 2111\n  elif category == 4:\n    sample_per_category = 2111\n  else:\n    sample_per_category = 2111\n  x_train_subset = x_train[x_train['score'] == category]\n  x_train_subset = x_train_subset.sample(n=sample_per_category,replace=False)\n  balanced_df = pd.concat([balanced_df,x_train_subset],ignore_index=True)\n  "

In [ ]:
balanced_df

fips        date  PRECTOT      PS  ...  WS50M_MIN  WS50M_RANGE  score  label
0      42005  2004-08-31     0.81   96.88  ...       2.58         1.31      0      A
1      19067  2003-04-22     0.00   97.72  ...       1.62         6.10      1      A
2      38071  2002-09-10     0.01   96.59  ...       2.79         5.07      0      A
3      48467  2009-09-08     0.00   99.63  ...       1.68         4.86      0      A
4      36005  2004-03-30     3.22  101.92  ...       4.39         1.64      0      A
...      ...         ...      ...     ...  ...        ...          ...    ...    ...
30292   6039  2016-02-16     0.00   91.22  ...       1.60         5.08      5      C
30293  31113  2013-03-05     0.00   92.36  ...       2.70        16.61      5      C
30294   8009  2012-08-07     0.70   86.70  ...       0.53         6.32      4      C
30295  13063  2007-07-17     5.39   98.50  ...       1.27         3.43      4      C
30296  56031  2003-03-18    17.45   83.25  ...       6.68         6.40      4      C

[30297 rows x 22 columns]

In [ ]:
scores = balanced_df['score']

In [ ]:
balanced_df

fips        date  PRECTOT      PS  ...  WS50M_MIN  WS50M_RANGE  score  label
0      22091  2005-07-05    14.98  100.92  ...       2.80         4.75      0      A
1       8117  2001-10-16     0.02   71.41  ...       2.70         3.16      0      A
2      48365  2010-01-05     0.00  101.87  ...       1.63         2.32      0      A
3      17189  2015-04-21     0.45   99.28  ...       7.62         2.98      0      A
4      24009  2006-04-18     0.00  100.77  ...       2.25         3.87      1      A
...      ...         ...      ...     ...  ...        ...          ...    ...    ...
30292  13265  2008-08-19     0.03   99.60  ...       0.68         5.19      4      C
30293   5003  2000-10-03     0.00  100.92  ...       2.84         4.12      4      C
30294  56025  2002-11-26     0.18   81.80  ...       4.39         3.12      4      C
30295  20187  2002-08-27     0.18   89.89  ...       5.30         5.58      4      C
30296  16073  2003-12-16     0.20   87.39  ...       5.42         2.79      4      C

[30297 rows x 22 columns]

In [ ]:
#balanced dataset with only label
#scores = balanced_df['score']
balanced_bands_df = balanced_df.drop('score',axis=1)
balanced_bands_df

fips        date  PRECTOT  ...  WS50M_MIN  WS50M_RANGE  label
0      51077  2007-03-06     0.00  ...       1.03         7.77      A
1      48451  2007-04-17     0.89  ...       5.57         6.05      A
2      55111  2008-09-23     0.02  ...       5.59         3.50      A
3       8037  2000-08-01     0.58  ...       0.66         4.24      A
4      25023  2005-01-18     0.00  ...       6.31         5.05      A
...      ...         ...      ...  ...        ...          ...    ...
30292  31041  2013-02-12     0.00  ...       5.76         3.67      C
30293  31179  2013-02-26     0.05  ...       1.34         6.44      C
30294  31075  2002-10-22     1.56  ...       5.06         3.39      C
30295  35033  2011-06-28     0.10  ...       1.76         6.53      C
30296  37197  2002-07-23     7.25  ...       0.95         2.83      C

[30297 rows x 21 columns]

In [ ]:
balanced_bands_df.to_csv('balanced_train_data.csv',index=False)

In [ ]:
features = balanced_bands_df.drop('label',axis=1)
label = balanced_bands_df['label']

# Test Data/Misc

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/Drought Prediction Data/test_downloadable.csv')

In [ ]:
test

label   fips                 date  ...  WS50M_MAX  WS50M_MIN  WS50M_RANGE
0         2   6031  1401753600000000000  ...       5.69       1.67         4.01
1         1  41029  1435017600000000000  ...       4.50       0.63         3.87
2         1  51099  1011052800000000000  ...       7.78       4.30         3.48
3         0  30057  1234828800000000000  ...       5.19       1.90         3.29
4         1  38103  1211846400000000000  ...       7.46       2.34         5.12
...     ...    ...                  ...  ...        ...        ...          ...
6055      1  31073  1107820800000000000  ...       4.65       0.11         4.54
6056      2  20129  1150761600000000000  ...      17.64       9.19         8.45
6057      1  30065  1081209600000000000  ...      11.96       1.02        10.94
6058      2  48255  1142294400000000000  ...      10.06       6.11         3.95
6059      2  31093  1364256000000000000  ...       9.85       1.10         8.75

[6060 rows x 21 columns]

In [ ]:
test[test['label']==2]

label   fips                 date  ...  WS50M_MAX  WS50M_MIN  WS50M_RANGE
0         2   6031  1401753600000000000  ...       5.69       1.67         4.01
5         2  13157  1029801600000000000  ...       3.98       0.54         3.44
6         2  48259  1163462400000000000  ...       9.24       5.76         3.48
8         2  27137  1164067200000000000  ...       7.20       1.70         5.49
12        2  48239  1252368000000000000  ...       5.44       1.87         3.57
...     ...    ...                  ...  ...        ...        ...          ...
6046      2  48303  1401148800000000000  ...       8.51       1.78         6.73
6052      2  13177  1316476800000000000  ...       6.78       4.19         2.59
6056      2  20129  1150761600000000000  ...      17.64       9.19         8.45
6058      2  48255  1142294400000000000  ...      10.06       6.11         3.95
6059      2  31093  1364256000000000000  ...       9.85       1.10         8.75

[2017 rows x 21 columns]

In [ ]:
category_a_train = balanced_df[balanced_df['label']=='A']

In [ ]:
len(category_a_train[category_a_train['score']==1])

1915

In [ ]:
category_b_train = balanced_df[balanced_df['label']=='B']

In [ ]:
category_c_train = balanced_df[balanced_df['label']=='C']

In [ ]:
category_b_train[category_b_train['score']==3]

fips        date  PRECTOT      PS  ...  WS50M_MIN  WS50M_RANGE  label  score
10100  28159  2010-10-26     8.52   99.12  ...       0.82         9.66      B      3
10106  40089  2013-02-12    12.57   98.62  ...       2.78         4.23      B      3
10109  17201  2003-04-29     5.24   98.65  ...       1.32         7.61      B      3
10111  53071  2005-07-12     0.00   94.39  ...       4.55         2.59      B      3
10116  13059  2002-02-05     0.97  100.49  ...       0.38         3.99      B      3
...      ...         ...      ...     ...  ...        ...          ...    ...    ...
20187  37055  2011-07-26     7.31  100.93  ...       3.27         4.35      B      3
20190   6087  2015-07-07     0.14  100.13  ...       4.02         2.39      B      3
20191  13211  2007-06-05     3.00   98.55  ...       2.52         3.47      B      3
20194  48359  2004-01-27     0.00   88.30  ...       2.06         7.90      B      3
20195  22043  2011-12-06     1.22  101.57  ...       2.62         2.14      B      3

[4034 rows x 22 columns]

In [ ]:
balanced_train_df_a = pd.DataFrame()
for category in np.unique(category_a_train['score']):
  if category == 0:
    sample_per_category = 1915
  else:
    sample_per_category = 1915
  x_train_subset_a = category_a_train[category_a_train['score'] == category]
  x_train_subset_a = x_train_subset_a.sample(n=sample_per_category,replace=False)
  balanced_train_df_a = pd.concat([balanced_train_df_a,x_train_subset_a],ignore_index=True)

In [ ]:
balanced_train_df_a = balanced_train_df_a.drop('label',axis=1)
balanced_train_df_a

fips        date  PRECTOT  ...  WS50M_MIN  WS50M_RANGE  score
0     26081  2009-12-29     0.00  ...       3.30         4.63      0
1     18001  2012-01-10     0.00  ...       3.07         6.16      0
2     46051  2003-07-22     0.37  ...       3.28         3.98      0
3     21075  2002-12-03     1.59  ...       6.09         2.89      0
4     42057  2003-12-30     2.84  ...       4.23         6.03      0
...     ...         ...      ...  ...        ...          ...    ...
3825  12023  2009-10-27     9.39  ...       3.26         3.29      1
3826  19169  2003-08-19     0.63  ...       3.89         3.91      1
3827  40119  2013-06-11     0.00  ...       6.86         4.26      1
3828  35055  2008-12-16     9.47  ...       6.02         5.41      1
3829  54011  2005-12-06     0.03  ...       1.73         2.65      1

[3830 rows x 21 columns]

In [ ]:
balanced_train_df_a.to_csv('balanced_a_train_data.csv',index=False)

In [ ]:
balanced_train_df_b = pd.DataFrame()
for category in np.unique(category_b_train['score']):
  if category == 2:
    sample_per_category = 4034
  else:
    sample_per_category = 4034
  x_train_subset_b = category_b_train[category_b_train['score'] == category]
  x_train_subset_b = x_train_subset_b.sample(n=sample_per_category,replace=False)
  balanced_train_df_b = pd.concat([balanced_train_df_b,x_train_subset_b],ignore_index=True)

In [ ]:
balanced_train_df_b = balanced_train_df_b.drop('label',axis=1)

In [ ]:
balanced_train_df_b.to_csv('balanced_b_train_data.csv',index=False)

In [ ]:
balanced_train_df_c = pd.DataFrame()
for category in np.unique(category_c_train['score']):
  if category == 4:
    sample_per_category = 2111
  else:
    sample_per_category = 2111
  x_train_subset_c = category_c_train[category_c_train['score'] == category]
  x_train_subset_c = x_train_subset_c.sample(n=sample_per_category,replace=False)
  balanced_train_df_c = pd.concat([balanced_train_df_c,x_train_subset_c],ignore_index=True)

In [ ]:
balanced_train_df_c = balanced_train_df_c.drop('label',axis=1)

In [ ]:
balanced_train_df_c.to_csv('balanced_c_train_data.csv',index=False)

# Training, Testing Top Level AI

In [ ]:
#Top Level AI
from sklearn.model_selection import train_test_split, validation_curve, GridSearchCV

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
x = balanced_bands_df.drop(['label','date'],axis=1)
y = balanced_bands_df['label']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
#model = SVC()
#model.fit(x_train,y_train)
rfc = RandomForestClassifier(n_estimators=1500,max_depth=100)
rfc.fit(x_train,y_train)

RandomForestClassifier(max_depth=100, n_estimators=1500)

In [ ]:
#x_test = balanced_test_df.drop(['label','date','score'],axis=1)
#y_test = balanced_test_df['label']
preds = rfc.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,preds))
print(classification_report(y_test,preds))

[[1344  364  292]
 [ 574  830  639]
 [ 234  405 1378]]
              precision    recall  f1-score   support

           A       0.62      0.67      0.65      2000
           B       0.52      0.41      0.46      2043
           C       0.60      0.68      0.64      2017

    accuracy                           0.59      6060
   macro avg       0.58      0.59      0.58      6060
weighted avg       0.58      0.59      0.58      6060



In [ ]:
x_test

fips  PRECTOT      PS  QV2M  ...  WS50M  WS50M_MAX  WS50M_MIN  WS50M_RANGE
25983   6031     0.01   98.92  4.71  ...   3.07       5.69       1.67         4.01
10821  41029     0.00   89.87  6.23  ...   2.56       4.50       0.63         3.87
18698  51099     0.00  100.73  3.95  ...   5.75       7.78       4.30         3.48
1804   30057     1.82   77.77  2.63  ...   3.49       5.19       1.90         3.29
10319  38103     0.01   96.81  3.58  ...   4.30       7.46       2.34         5.12
...      ...      ...     ...   ...  ...    ...        ...        ...          ...
14417  31073     1.77   93.22  1.70  ...   3.08       4.65       0.11         4.54
28355  20129     0.02   89.27  6.95  ...  13.28      17.64       9.19         8.45
12340  30065     0.05   89.95  5.24  ...   6.33      11.96       1.02        10.94
29295  48255     0.00  101.13  3.19  ...   7.62      10.06       6.11         3.95
29871  31093     0.00   94.91  1.80  ...   5.03       9.85       1.10         8.75

[6060 rows x 19 columns]

In [ ]:
param_grid = {'n_estimators':[100,200,500,1000],'max_depth':[100]}
grid = GridSearchCV(RandomForestClassifier(),param_grid,cv=3)

In [ ]:
grid.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [100],
                         'n_estimators': [100, 200, 500, 1000]})

In [ ]:
grid.best_params_

{'max_depth': 100, 'n_estimators': 1000}

In [ ]:
grid_predicts = grid.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,grid_predicts))
print(classification_report(y_test,grid_predicts))

[[2036  609  383]
 [ 888 1214  948]
 [ 354  635 2023]]
              precision    recall  f1-score   support

           A       0.62      0.67      0.65      3028
           B       0.49      0.40      0.44      3050
           C       0.60      0.67      0.64      3012

    accuracy                           0.58      9090
   macro avg       0.57      0.58      0.57      9090
weighted avg       0.57      0.58      0.57      9090



In [ ]:
index = x_test.index
#index
scores_indexes = []
for i in index:
  scores_indexes.append(score[i])

len(scores_indexes)

6060

In [ ]:
x_test['score'] = scores_indexes

In [ ]:
x_test['label'] = preds#train data for sub category AI's has the label as the predictions from top level AI
x_test

fips  PRECTOT      PS  QV2M  ...  WS50M_MIN  WS50M_RANGE  score  label
25983   6031     0.01   98.92  4.71  ...       1.67         4.01      5      B
10821  41029     0.00   89.87  6.23  ...       0.63         3.87      2      B
18698  51099     0.00  100.73  3.95  ...       4.30         3.48      2      A
1804   30057     1.82   77.77  2.63  ...       1.90         3.29      1      C
10319  38103     0.01   96.81  3.58  ...       2.34         5.12      2      A
...      ...      ...     ...   ...  ...        ...          ...    ...    ...
14417  31073     1.77   93.22  1.70  ...       0.11         4.54      3      C
28355  20129     0.02   89.27  6.95  ...       9.19         8.45      4      C
12340  30065     0.05   89.95  5.24  ...       1.02        10.94      3      B
29295  48255     0.00  101.13  3.19  ...       6.11         3.95      5      C
29871  31093     0.00   94.91  1.80  ...       1.10         8.75      5      C

[6060 rows x 21 columns]

In [ ]:
train_a_data = x_test[x_test['label']=='A']

In [ ]:
len(train_a_data[train_a_data['score']==5])

38

In [ ]:
train_a_data.to_csv('category_a_train_data.csv',index=False)

In [ ]:
train_b_data = x_test[x_test['label']=='B']

In [ ]:
train_b_data.to_csv('category_b_train_data.csv',index=False)

In [ ]:
train_c_data = x_test[x_test['label']=='C']

In [ ]:
train_c_data.to_csv('category_c_train_data.csv',index=False)

# Balancing, Training, Testing Sub-Category AI's

In [ ]:
x_a = train_a_data.drop(['label','score'],axis=1)
y_a = train_a_data['score']
x_train_a,x_test_a,y_train_a,y_test_a = train_test_split(x_a,y_a,test_size=0.2)

In [ ]:
#Category A AI
rfc_A = RandomForestClassifier(n_estimators=1500,max_depth=100)
rfc_A.fit(x_train_a,y_train_a)

RandomForestClassifier(max_depth=100, n_estimators=1500)

In [ ]:
#x_test_a = balanced_test_df_a.drop(['date','label','score'],axis=1)
#y_test_a = balanced_test_df_a['score']
preds_a = rfc_A.predict(x_test_a)
print(confusion_matrix(y_test_a,preds_a))
print(classification_report(y_test_a,preds_a))

[[340   0  17   0   0   0]
 [ 45   1   2   0   0   0]
 [107   3  14   1   3   0]
 [ 61   0   2   0   1   0]
 [ 53   0   4   0   3   0]
 [  7   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.55      0.95      0.70       357
           1       0.25      0.02      0.04        48
           2       0.36      0.11      0.17       128
           3       0.00      0.00      0.00        64
           4       0.43      0.05      0.09        60
           5       0.00      0.00      0.00         7

    accuracy                           0.54       664
   macro avg       0.27      0.19      0.17       664
weighted avg       0.42      0.54      0.42       664



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
x_b = train_b_data.drop(['label','score'],axis=1)
y_b = train_b_data['score']
x_train_b,x_test_b,y_train_b,y_test_b = train_test_split(x_b,y_b,test_size=0.2)

In [ ]:
#Category B AI
rfc_B = RandomForestClassifier(n_estimators=1500,max_depth=100)
rfc_B.fit(x_train_b,y_train_b)

RandomForestClassifier(max_depth=100, n_estimators=1500)

In [ ]:
#x_test_b = balanced_test_df_b.drop(['date','label','score'],axis=1)
#y_test_b = balanced_test_df_b['score']
preds_B = rfc_B.predict(x_test_b)
print(confusion_matrix(y_test_b,preds_B))
print(classification_report(y_test_b,preds_B))

[[12  1 37 12 17  0]
 [ 3  0 16  2  9  0]
 [20  0 85 19 42  1]
 [10  0 39 15 22  0]
 [ 6  0 40 18 38  0]
 [ 1  0 14  2  3  1]]
              precision    recall  f1-score   support

           0       0.23      0.15      0.18        79
           1       0.00      0.00      0.00        30
           2       0.37      0.51      0.43       167
           3       0.22      0.17      0.19        86
           4       0.29      0.37      0.33       102
           5       0.50      0.05      0.09        21

    accuracy                           0.31       485
   macro avg       0.27      0.21      0.20       485
weighted avg       0.29      0.31      0.28       485



In [ ]:
x_c = train_c_data.drop(['label','score'],axis=1)
y_c = train_c_data['score']
x_train_c,x_test_c,y_train_c,y_test_c = train_test_split(x_c,y_c,test_size=0.2)

In [ ]:
#Category C AI
rfc_C = RandomForestClassifier(n_estimators=1000,max_depth=100)
rfc_C.fit(x_train_c,y_train_c)

RandomForestClassifier(max_depth=100, n_estimators=1000)

In [ ]:
#x_test_c = balanced_test_df_c.drop(['date','label','score'],axis=1)
#y_test_c = balanced_test_df_c['score']
preds_C = rfc_C.predict(x_test_c)
print(confusion_matrix(y_test_c,preds_C))
print(classification_report(y_test_c,preds_C))

[[  0   0   2   0  55   2]
 [  1   0   1   0  16   0]
 [  1   0   3   4  87   6]
 [  0   0   2   3  80   4]
 [  1   0   5  12 269  15]
 [  1   0   0   1  77  22]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        59
           1       0.00      0.00      0.00        18
           2       0.23      0.03      0.05       101
           3       0.15      0.03      0.06        89
           4       0.46      0.89      0.61       302
           5       0.45      0.22      0.29       101

    accuracy                           0.44       670
   macro avg       0.22      0.20      0.17       670
weighted avg       0.33      0.44      0.33       670



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
def launch_fe(data):
    import os
    import pandas as pd
    from io import StringIO
    import json
    from sklearn.model_selection import train_test_split
    from sklearn.feature_extraction.text import CountVectorizer
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.impute import SimpleImputer
    from sklearn.preprocessing import OneHotEncoder
    from sklearn.feature_extraction import text
    import pickle
    from scipy import sparse
    MAX_TEXT_FEATURES = 200
    columns_list = ["label", "fips", "PRECTOT", "PS", "QV2M", "T2M", "T2MDEW", "T2MWET", "T2M_MAX", "T2M_MIN", "T2M_RANGE", "TS", "WS10M", "WS10M_MAX", "WS10M_MIN", "WS10M_RANGE", "WS50M", "WS50M_MAX", "WS50M_MIN", "WS50M_RANGE", "date"]

    dataset = pd.read_csv(data,skipinitialspace=True)
    num_samples = len(dataset)

    date_time_features = ["date"]
    for feature in date_time_features:
        dataset[feature] = pd.to_datetime(dataset[feature])
        dataset[feature] = dataset[feature].apply(lambda x: x.value)

    # Encode labels into numbers starting with 0
    #label = "label"
    #tmpCol = dataset[label].astype('category')
    #dict_encoding = { label: dict(enumerate(tmpCol.cat.categories))}
    # Save the model
    #model_name = "daaf3105-b999-4c06-982a-a9f7be38f25a"
    #fh = open(model_name, "wb")
    #pickle.dump(dict_encoding, fh)
    #fh.close()

    #label = "label"
    #dataset[label] = tmpCol.cat.codes

    # Move the label column
    #cols = list(dataset.columns)
    #colIdx = dataset.columns.get_loc("label")
    # Do nothing if the label is in the 0th position
    # Otherwise, change the order of columns to move label to 0th position
    #if colIdx != 0:
        #cols = cols[colIdx:colIdx+1] + cols[0:colIdx] + cols[colIdx+1:]
        #dataset = dataset[cols]

    # split dataset into train and test
    train, test = train_test_split(dataset, test_size=0.2, random_state=42)

    # Write train and test csv
    train.to_csv('train.csv')
    test.to_csv('test.csv')
    column_names = list(train.columns)
"""
def get_model_id():
    return "daaf3105-b999-4c06-982a-a9f7be38f25a"
"""

'\ndef get_model_id():\n    return "daaf3105-b999-4c06-982a-a9f7be38f25a"\n'

In [ ]:
# Upload a correct file from your local machine
from io import BytesIO
from google.colab import files
uploaded_file = files.upload()
for name in uploaded_file.keys():
    filename = name
data = BytesIO(uploaded_file[filename])

launch_fe(data)

Saving balanced_train_data.csv to balanced_train_data (1).csv


In [ ]:
# import the library of the algorithm
from sklearn.ensemble import RandomForestClassifier
# Initialize hyperparams
max_depth = 100
max_depth = 2 if not max_depth else max_depth

n_estimators = 1500
n_estimators = 100 if not n_estimators else n_estimators
# Initialize the algorithm
model = RandomForestClassifier(max_depth=max_depth, random_state=0, n_estimators=n_estimators)

In [ ]:
import pandas as pd
# Load the test and train datasets
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [ ]:
train['index'] = train['Unnamed: 0']
train

Unnamed: 0   fips                 date  ...  WS50M_RANGE  label  index
0            5194  20125  1453766400000000000  ...         5.22      A   5194
1            4057  54077  1386028800000000000  ...         3.79      A   4057
2           26241  13129  1185840000000000000  ...         1.98      C  26241
3           26290  22093  1150761600000000000  ...         2.65      C  26290
4           15974  36033  1476144000000000000  ...         4.05      B  15974
...           ...    ...                  ...  ...          ...    ...    ...
24232       29802  37183  1197936000000000000  ...         4.12      C  29802
24233        5390  37181  1083024000000000000  ...         5.71      A   5390
24234         860   1061   991094400000000000  ...         3.49      A    860
24235       15795  37157  1354579200000000000  ...         4.53      B  15795
24236       23654  30103  1110844800000000000  ...         7.08      C  23654

[24237 rows x 23 columns]

In [ ]:
train = train.drop('Unnamed: 0',axis=1)

In [ ]:
indexes = train['index']

In [ ]:
indexes

0         5194
1         4057
2        26241
3        26290
4        15974
         ...  
24232    29802
24233     5390
24234      860
24235    15795
24236    23654
Name: index, Length: 24237, dtype: int64

In [ ]:
x_train = train.drop(['label','index'],axis=1)

In [ ]:
x_train

fips                 date  PRECTOT  ...  WS50M_MAX  WS50M_MIN  WS50M_RANGE
0      20125  1453766400000000000     0.00  ...       7.19       1.97         5.22
1      54077  1386028800000000000     0.02  ...       5.47       1.68         3.79
2      13129  1185840000000000000     1.51  ...       3.49       1.51         1.98
3      22093  1150761600000000000     2.18  ...       5.71       3.06         2.65
4      36033  1476144000000000000     0.00  ...       4.88       0.83         4.05
...      ...                  ...      ...  ...        ...        ...          ...
24232  37183  1197936000000000000     0.00  ...       5.40       1.27         4.12
24233  37181  1083024000000000000     0.22  ...       8.66       2.95         5.71
24234   1061   991094400000000000     3.49  ...       7.00       3.51         3.49
24235  37157  1354579200000000000     0.00  ...       7.35       2.81         4.53
24236  30103  1110844800000000000     0.26  ...       8.37       1.29         7.08

[24237 rows x 20 columns]

In [ ]:
y_train = train['label']

In [ ]:
test['index'] = test['Unnamed: 0']

In [ ]:
test = test.drop('Unnamed: 0',axis=1)
test_indexes = test['index']

In [ ]:
x_test = test.drop(['label','index'],axis=1)
y_test = test['label']

In [ ]:
model.fit(x_train,y_train)

RandomForestClassifier(max_depth=100, n_estimators=1500, random_state=0)

In [ ]:
# Predict the class labels
y_pred = model.predict(x_test)
# import the library to calculate confusion_matrix
from sklearn.metrics import confusion_matrix, classification_report
# calculate confusion matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
#encoded_matrix = encode_confusion_matrix(confusion_matrix)
print(confusion_matrix)
# calculate accuracy
score = model.score(x_test,y_test)
# The value is returned as a decimal value between 0 and 1
# converting to percentage
accuracy = score * 100
print('Accuracy of the model is: ', accuracy)

[[1500  386  114]
 [ 495 1061  487]
 [ 137  281 1599]]
Accuracy of the model is:  68.64686468646865


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           A       0.70      0.75      0.73      2000
           B       0.61      0.52      0.56      2043
           C       0.73      0.79      0.76      2017

    accuracy                           0.69      6060
   macro avg       0.68      0.69      0.68      6060
weighted avg       0.68      0.69      0.68      6060



In [ ]:
x_test['index'] = test_indexes

In [ ]:
x_test['label'] = y_pred

In [ ]:
test_indexes

0       25983
1       10821
2       18698
3        1804
4       10319
        ...  
6055    14417
6056    28355
6057    12340
6058    29295
6059    29871
Name: index, Length: 6060, dtype: int64

In [ ]:
#index = x_test.index
#index
scores_indexes = []
#test_indexes[0].astype(int)
scores = balanced_df['score']

In [ ]:
scores

0        0
1        0
2        0
3        0
4        1
        ..
30292    4
30293    4
30294    4
30295    4
30296    4
Name: score, Length: 30297, dtype: int64

In [ ]:
scores_indexes = []
for i in test_indexes:
  scores_indexes.append(scores[i])

In [ ]:
x_test['score'] = scores_indexes

In [ ]:
x_test

fips                 date  PRECTOT  ...  index  label  score
0      6031  1401753600000000000     0.01  ...  25983      C      5
1     41029  1435017600000000000     0.00  ...  10821      B      2
2     51099  1011052800000000000     0.00  ...  18698      B      2
3     30057  1234828800000000000     1.82  ...   1804      A      1
4     38103  1211846400000000000     0.01  ...  10319      B      2
...     ...                  ...      ...  ...    ...    ...    ...
6055  31073  1107820800000000000     1.77  ...  14417      B      3
6056  20129  1150761600000000000     0.02  ...  28355      C      4
6057  30065  1081209600000000000     0.05  ...  12340      B      3
6058  48255  1142294400000000000     0.00  ...  29295      C      5
6059  31093  1364256000000000000     0.00  ...  29871      C      5

[6060 rows x 23 columns]

In [ ]:
a = x_test[x_test['label']=='A']

In [ ]:
a

fips                 date  PRECTOT  ...  index  label  score
3     30057  1234828800000000000     1.82  ...   1804      A      1
8     27137  1164067200000000000     0.47  ...  22030      A      4
13    54063  1225756800000000000     0.12  ...  15544      A      2
16    39169  1482192000000000000     0.00  ...   6440      A      0
20    28037  1366675200000000000     0.32  ...   6334      A      0
...     ...                  ...      ...  ...    ...    ...    ...
6043  28097  1451952000000000000     0.00  ...   6280      A      0
6044  48373  1185235200000000000     0.00  ...   9022      A      0
6047  12027  1264464000000000000     0.02  ...   1259      A      0
6049  48175  1079395200000000000     0.05  ...   9938      A      0
6051  13169  1133222400000000000     3.47  ...   5729      A      0

[2132 rows x 23 columns]

In [ ]:
b = x_test[x_test['label']=='B']

In [ ]:
c = x_test[x_test['label']=='C']

In [ ]:
train_a,test_a = train_test_split(a,test_size=0.2,random_state=42)

In [ ]:
# Initialize hyperparams
max_depth_a = 100
max_depth_a = 2 if not max_depth_a else max_depth_a

n_estimators_a = 1500
n_estimators_a = 100 if not n_estimators_a else n_estimators_a
# Initialize the algorithm
rfc_A = RandomForestClassifier(max_depth=max_depth_a, random_state=0, n_estimators=n_estimators_a)

In [ ]:
train_a_features = train_a.drop(['label','score','index'],axis=1)

In [ ]:
train_a_label = train_a['score']

In [ ]:
test_a_features = test_a.drop(['label','score','index'],axis=1)
test_a_label = test_a['score']

In [ ]:
test_a_features

fips                 date  PRECTOT  ...  WS50M_MAX  WS50M_MIN  WS50M_RANGE
781   39057  1378771200000000000     0.07  ...       8.19       4.65         3.53
5727  13271  1044316800000000000     1.97  ...      10.49       6.40         4.09
4856  13139  1173744000000000000     0.00  ...       5.94       0.09         5.84
4732  46085  1035244800000000000     5.45  ...       6.49       4.23         2.25
5794  26119  1362441600000000000     0.08  ...       7.37       5.59         1.78
...     ...                  ...      ...  ...        ...        ...          ...
5501  21091  1360627200000000000     0.20  ...       7.19       0.13         7.06
1760  28045  1006214400000000000     0.30  ...       7.08       3.75         3.34
6012  27129  1162857600000000000     0.05  ...       9.91       1.69         8.22
549   50019  1131408000000000000     0.88  ...       7.61       3.22         4.39
1907  20105  1133222400000000000     0.00  ...      15.29       0.75        14.53

[427 rows x 20 columns]

In [ ]:
rfc_A.fit(train_a_features,train_a_label)

RandomForestClassifier(max_depth=100, n_estimators=1500, random_state=0)

In [ ]:
preds_a = rfc_A.predict(test_a_features)

In [ ]:
test_a_label

781     0
5727    1
4856    1
4732    2
5794    0
       ..
5501    0
1760    0
6012    1
549     0
1907    0
Name: score, Length: 427, dtype: int64

In [ ]:
# calculate confusion matrix
confusion_matrix = confusion_matrix(test_a_label, preds_a)
#encoded_matrix = encode_confusion_matrix(confusion_matrix)
print(confusion_matrix)
# calculate accuracy
score = model.score(test_a_features,test_a_label)
# The value is returned as a decimal value between 0 and 1
# converting to percentage
accuracy = score * 100
print('Accuracy of the model is: ', accuracy)

TypeError: ignored

In [ ]:
print(classification_report(test_a_label))

# Combination

In [ ]:
import requests
import json

def get_prediction(data={"fips":28522,"date":"2000-01-04","PRECTOT":43.9,"PS":85.625,"QV2M":11.065,"T2M":4.725000000000001,"T2MDEW":-1.58,"T2MWET":-1.504999999999999,"T2M_MAX":11.409999999999998,"T2M_MIN":-3.290000000000001,"T2M_RANGE":14.56,"TS":5.449999999999999,"WS10M":7.985,"WS10M_MAX":10.01,"WS10M_MIN":6.135,"WS10M_RANGE":8.120000000000001,"WS50M":9.99,"WS50M_MAX":13.005,"WS50M_MIN":7.625,"WS50M_RANGE":10.120000000000001}):
  url = 'https://askai.aiclub.world/2453a4f5-ff1c-4bb3-985a-e760acdd0fed'
  r = requests.post(url, data=json.dumps(data))
  response = getattr(r,'_content').decode("utf-8")
  #print(response)
  return response

In [ ]:
import requests
import json

def get_prediction_a(data={"fips":28524,"date":"2000-01-04","PRECTOT":33.655,"PS":86.03,"QV2M":10.47,"T2M":3.7049999999999983,"T2MDEW":-0.6800000000000015,"T2MWET":-0.6450000000000014,"T2M_MAX":11.545000000000002,"T2M_MIN":-2.4049999999999994,"T2M_RANGE":14.615,"TS":3.914999999999999,"WS10M":7.235,"WS10M_MAX":9.195,"WS10M_MIN":6.145,"WS10M_RANGE":7.325,"WS50M":9.01,"WS50M_MAX":11.34,"WS50M_MIN":7.569999999999999,"WS50M_RANGE":9.01}):
  url = 'https://askai.aiclub.world/b872c0f6-da90-409a-82fd-5eccb73b881b'
  r = requests.post(url, data=json.dumps(data))
  response = getattr(r,'_content').decode("utf-8")
  #print(response)
  return response

In [ ]:
import requests
import json

def get_prediction_b(data={"fips":28522,"date":"2000-01-04","PRECTOT":41.245,"PS":86.2,"QV2M":10.15,"T2M":4.885000000000002,"T2MDEW":-1.5950000000000006,"T2MWET":-1.4600000000000009,"T2M_MAX":12.59,"T2M_MIN":-3.084999999999999,"T2M_RANGE":13.795,"TS":4.809999999999999,"WS10M":6.91,"WS10M_MAX":9.225000000000001,"WS10M_MIN":5.42,"WS10M_RANGE":8.175,"WS50M":8.870000000000001,"WS50M_MAX":11.725,"WS50M_MIN":7.625,"WS50M_RANGE":10.15}):
  url = 'https://askai.aiclub.world/7addeb71-1780-41a0-b998-3bc9016cacdf'
  r = requests.post(url, data=json.dumps(data))
  response = getattr(r,'_content').decode("utf-8")
  #print(response)
  return response

In [ ]:
import requests
import json

def get_prediction_c(data={"fips":28522,"date":"2000-05-16","PRECTOT":43.9,"PS":86.33,"QV2M":10.7,"T2M":10.670000000000002,"T2MDEW":2.7699999999999996,"T2MWET":3.17,"T2M_MAX":16.525,"T2M_MIN":3.5299999999999994,"T2M_RANGE":13.110000000000001,"TS":11.370000000000001,"WS10M":6.67,"WS10M_MAX":10.139999999999999,"WS10M_MIN":4.61,"WS10M_RANGE":7.175000000000001,"WS50M":8.770000000000001,"WS50M_MAX":13.315000000000001,"WS50M_MIN":6.075,"WS50M_RANGE":8.9}):
  url = 'https://askai.aiclub.world/5ad6b521-f64c-4e2e-8b5f-d3528dbcf302'
  r = requests.post(url, data=json.dumps(data))
  response = getattr(r,'_content').decode("utf-8")
  #print(response)
  return response

In [ ]:
features

fips        date  PRECTOT  ...  WS50M_MAX  WS50M_MIN  WS50M_RANGE
0      48099  2004-09-07     0.00  ...       9.94       7.42         2.52
1      31019  2010-06-29     0.00  ...       8.75       3.49         5.25
2      53023  2007-04-03     0.04  ...       5.27       0.40         4.87
3      51159  2001-10-23     0.01  ...       6.89       2.11         4.78
4      51175  2013-08-06     5.62  ...       5.52       3.01         2.51
...      ...         ...      ...  ...        ...        ...          ...
30292  48103  2002-01-08     0.00  ...       7.24       1.83         5.41
30293  13141  2016-12-13    13.71  ...       3.18       0.85         2.33
30294  13037  2011-06-28     5.56  ...       4.68       2.92         1.77
30295   6007  2014-06-17     0.00  ...       7.04       3.18         3.86
30296  48197  2012-02-14     0.42  ...       7.68       0.98         6.70

[30297 rows x 20 columns]

In [ ]:
features = features.sample(n=5000,random_state=42,ignore_index=False)

In [ ]:
features

fips        date  PRECTOT  ...  WS50M_MAX  WS50M_MIN  WS50M_RANGE
22510  48227  2011-04-12     0.00  ...      11.15       5.27         5.88
15162  35015  2000-05-23     0.00  ...      11.40       5.61         5.80
8789   18057  2010-02-09     6.13  ...      11.94       0.74        11.20
2103   13167  2001-09-18     0.02  ...       4.26       0.99         3.27
11446  13109  2011-04-12     2.31  ...      10.66       5.11         5.55
...      ...         ...      ...  ...        ...        ...          ...
2239   46109  2014-04-29     3.26  ...      13.79       8.45         5.35
4039   19003  2012-01-17     1.18  ...      13.57       1.68        11.89
27763  17103  2005-07-19     0.00  ...       7.15       1.62         5.53
25888   1041  2012-03-27     0.01  ...       6.19       1.64         4.56
15916  13093  2000-10-10     0.02  ...       5.44       0.60         4.84

[10000 rows x 20 columns]

In [ ]:
indexes = features.index

In [ ]:
indexes

Int64Index([25983, 10821, 18698,  1804, 10319, 23292, 21366,  6214, 22030,
            17780, 18672, 10378, 25020, 15544, 10221, 10198,  6440, 14711,
            17137, 19882,  6334,  3064, 13762, 12930, 19138,  5551, 20472,
            22980,  2876,  4449, 25180, 16580, 18903, 24227,  1227,  3470,
            26196,  5464, 20742, 14620, 10504, 20398, 26425, 14316,  4915,
            16734,  4186,  5545, 27706, 30240],
           dtype='int64')

In [ ]:
scores

0        0
1        0
2        0
3        0
4        1
        ..
30292    4
30293    4
30294    4
30295    4
30296    4
Name: score, Length: 30297, dtype: int64

In [ ]:
scores_list = []
for i in indexes:
  scores_list.append(scores[i])

len(scores_list)

50

In [ ]:
points = 0
points_a = 0
points_b = 0
points_c = 0
top_level_points = 0
count = 0
a_count = 0
b_count = 0
c_count = 0
for index, row in features.iterrows():
  rd = row.to_dict()
  composite_label = get_prediction(data=rd)
  composite_value = json.loads(json.loads(composite_label)['body'])['predicted_label']
  if composite_value == label[index]:
    top_level_points += 1
    if composite_value == 'A':
      composite_label_a = get_prediction_a(data=rd)
      composite_value_a = json.loads(json.loads(composite_label_a)['body'])['predicted_label']
      if composite_value_a == scores[index]:
        points += 1
        points_a += 1
        a_count += 1
        count += 1
        print(count, end=" ")
      else:
        a_count += 1
        count += 1
        print(count, end=" ")
    elif composite_value == 'B':
      composite_label_b = get_prediction_b(data=rd)
      composite_value_b = json.loads(json.loads(composite_label_b)['body'])['predicted_label']
      if composite_value_b == scores[index]:
        points += 1
        points_b += 1
        b_count += 1
        count += 1
        print(count,end=" ")
      else:
        b_count += 1
        count += 1
        print(count,end=" ")
    else:
      composite_label_c = get_prediction_c(data=rd)
      composite_value_c = json.loads(json.loads(composite_label_c)['body'])['predicted_label']
      if composite_value_c == scores[index]:
        points += 1
        points_c += 1
        c_count += 1
        count += 1
        print(count,end=" ")
      else:
        c_count += 1
        count += 1
        print(count,end=" ")
  else:
    count += 1
    print(count,end=" ")
    continue


total_values = len(features)
accuracy = points/total_values
top_level_accuracy = top_level_points/total_values
accuracy_a = points_a/a_count
accuracy_b = points_b/b_count
accuracy_c = points_c/c_count
print("Top level accuracy", top_level_accuracy)
print("Accuracy for Band A", accuracy_a)
print("Accuracy for Band B", accuracy_b)
print("Accuracy for Band C", accuracy_c)
print("Overall accuracy", accuracy)



1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 